services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    environment:
      - FLASK_ENV=production
    command: gunicorn -b 0.0.0.0:8000 app:app 
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    ports:
      - "80:80"
    depends_on:
      - backend
